name: "Actions AI"
description: "A GitHub Action to run a TypeScript project that compiles to JavaScript in the dist folder."
icon: "cpu" 
color: "blue" 

inputs:
  prompt:
    description: "The prompt to send to the Hugging Face API"
    required: true
    default: "Where is USA?"

outputs:
  response:
    description: "The response from the Hugging Face API"

runs:
  using: "node20"
  steps:
    - name: Install dependencies
      run: npm install

    - name: Run ChatGPT script
      run: node dist/chatgpt2.js
