name: Using chat gpt2

on:
  push:
    branches:
      - main

jobs:
  call_to_chat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install npm dependencies
      id: npm_install
      run: |
        npm install axios dotenv | tee install_output.txt

    - name: Capture npm install output as environment variable
      run: echo "install_output=$(cat install_output.txt)" >> $GITHUB_ENV

    - name: Run reusable ChatGPT action
      uses: P4dr4/ActionsAI@main 
      with:
        prompt: "${{ env.install_output }}"

    - name: Run tests
      run: npm test
