name: Using chat gpt2

on:
  push:
    branches:
      - main

jobs:
  npm_install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use ChatGPT reusable action
      uses: P4dr4/ActionsAI@main  
      with:
        prompt: "Where is USA?"
